### ISSUE TITLE
Fails on import

### ISSUE THREAD

**Issue by il-83** [trilogy-group/arch-as-code#108]
I'm newbie on arch-as-code and trying to import my workspace. And getting NPE at WorkspaceReader.java:112

https://github.com/trilogy-group/arch-as-code/blob/d3e60b6c97545bbd5cbc7a08e208727e91ebb30b/src/main/java/net/trilogy/arch/adapter/in/WorkspaceReader.java#L112

**Comment by il-83** [comment]
Stacktrace:

`$ arch-as-code import ~/Downloads/structurizr-50167-workspace.json .
java.lang.NullPointerException
	at net.trilogy.arch.adapter.in.WorkspaceReader.lambda$deploymentViews$6(WorkspaceReader.java:112)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.trilogy.arch.adapter.in.WorkspaceReader.deploymentViews(WorkspaceReader.java:116)
	at net.trilogy.arch.adapter.in.WorkspaceReader.load(WorkspaceReader.java:44)
	at net.trilogy.arch.commands.ImportCommand.call(ImportCommand.java:34)
	at net.trilogy.arch.commands.ImportCommand.call(ImportCommand.java:13)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at net.trilogy.arch.Application.execute(Application.java:48)
	at net.trilogy.arch.Application.main(Application.java:43)
`

**Comment by yogesh-dhamija** [comment]
Should be fixed in latest release: https://github.com/trilogy-group/arch-as-code/releases/tag/v1.2.4
