### ISSUE TITLE
Error When Publishing

### ISSUE THREAD

**Issue by dchwartz-optimal** [trilogy-group/arch-as-code#78]
I love the idea of C4, so I figured I would give a try. Structurizr seemed like a great option... and I picked the simplest Architecture as Code option: arch-as-code 

All was well, but when I publish, I get this error (I already checked the credentials.json and the workspace ID is correct, as are the keys) 

C:\Architecture>arch-as-code publish OptimalPlus 
Feb 12, 2020 9:32:47 AM net.nahknarmi.arch.commands.ValidateCommand call 
INFO: data-structure.yml is valid. 
java.lang.IllegalStateException: Workspace Id not found!! 
at net.nahknarmi.arch.transformation.ArchitectureDataStructureTransformer.lambda$toWorkSpace$0(ArchitectureDataS 
at java.base/java.util.Optional.orElseThrow(Optional.java:408) 
at net.nahknarmi.arch.transformation.ArchitectureDataStructureTransformer.toWorkSpace(ArchitectureDataStructureT 
at net.nahknarmi.arch.publish.ArchitectureDataStructurePublisher.publish(ArchitectureDataStructurePublisher.java 
at net.nahknarmi.arch.commands.PublishCommand.call(PublishCommand.java:31) 
at net.nahknarmi.arch.commands.PublishCommand.call(PublishCommand.java:11) 
at picocli.CommandLine.executeUserObject(CommandLine.java:1783) 
at picocli.CommandLine.access$900(CommandLine.java:145) 
at picocli.CommandLine$RunLast.handle(CommandLine.java:2141) 
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108) 
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975) 
at picocli.CommandLine.execute(CommandLine.java:1904) 
at net.nahknarmi.arch.Bootstrap.main(Bootstrap.java:14) 

Can you help?

**Comment by simonbrowndotje** [comment]
I thought I'd try this out, and I get the same error. The ```.arch-as-code``` directory (with the credentials file) created by the ```arch-as-code init``` command seems to be created in the wrong place, or the tool is looking in the wrong place. I moved the ```.arch-as-code``` directory from ```<PATH_TO_STORE_ARCHITECTURE_DOCUMENTATION>``` to the current directory, and everything started working.

**Comment by dchwartz-optimal** [comment]
Hi Simon,

Thank you so much for taking the time to figure this out for me.  I know it was not your code or your responsibility, so it means the world that you went out of your way for me.

David

**Comment by nahknarmi** [comment]
@dchwartz-optimal - Thanks so much for trying out the tool and letting me know about the issue! I've updated the documentation around getting started - please let me know if it helps.

@simonbrowndotje - finding out that you've taken time to tinker with our tool absolutely made my day! Huge fan of your work.

**Comment by simonbrowndotje** [comment]
Thanks @nahknarmi ... you're welcome! :-) BTW, if you'd like a free open source plan (3 public workspaces) for your arch-as-code documentation and tests, just send me an e-mail.

**Comment by nahknarmi** [comment]
Updated documentation with what I hope is more clear on getting started.
