### ISSUE TITLE
Large yaml fails on 'Connection Reset'

### ISSUE THREAD

**Issue by dchwartz-optimal** [trilogy-group/arch-as-code#85]
I was happily using arch-as-code to create my structurizr diagrams and it is working great.  When I got to a yaml that was about 9k characters in size, I fail with this message:

Feb 24, 2020 3:49:41 PM net.nahknarmi.arch.commands.ValidateCommand call
INFO: data-structure.yml is valid.
Feb 24, 2020 3:49:42 PM com.structurizr.api.StructurizrClient getWorkspace
INFO: Getting workspace with ID 50962
Feb 24, 2020 3:49:44 PM com.structurizr.view.ViewSet copyLayoutInformationFrom
WARNING: Could not find a matching view for "Data Loading - Containers" ... diagram layout information may be lost.
Feb 24, 2020 3:49:44 PM com.structurizr.api.StructurizrClient putWorkspace
INFO: Putting workspace with ID 50962
Feb 24, 2020 3:49:45 PM com.structurizr.api.StructurizrClient putWorkspace
SEVERE: javax.net.ssl.SSLProtocolException: Connection reset
com.structurizr.api.StructurizrClientException: javax.net.ssl.SSLProtocolException: Connection reset
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:376)
        at net.nahknarmi.arch.adapter.StructurizrAdapter.publish(StructurizrAdapter.java:38)
        at net.nahknarmi.arch.publish.ArchitectureDataStructurePublisher.publish(ArchitectureDataStructurePublisher.java:48)
        at net.nahknarmi.arch.commands.PublishCommand.call(PublishCommand.java:31)
        at net.nahknarmi.arch.commands.PublishCommand.call(PublishCommand.java:11)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at net.nahknarmi.arch.Bootstrap.main(Bootstrap.java:14)
Caused by: javax.net.ssl.SSLProtocolException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
        at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
        at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:241)
        at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
        at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:187)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:180)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:223)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:562)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:195)
        at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:106)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:171)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:164)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RetryExec.execute(RetryExec.java:87)

**Comment by simonbrowndotje** [comment]
A few questions:

- Which version of Java are you using?
- Do you have a proxy server on the network?
- Does this work on other networks that you have access to?

**Comment by dchwartz-optimal** [comment]
I am using 
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

I do not have a proxy server, but am on a VPN

I will try it on another network and report back

**Comment by dchwartz-optimal** [comment]
It does not work without the VPN either.

I also tried it on another network without success.

Please note: 
arch-as-code works great for the same file as long as I take out a few yaml nodes.  It seems to be related to size of the data in the put call to Structurizr

**Comment by simonbrowndotje** [comment]
Feel free to e-mail me your source YAML file (a version that fails; to help@structurizr.com), and I'll take a look.

**Comment by simonbrowndotje** [comment]
YAML received, and it works for me, although I'm on Oracle's JDK rather than OpenJDK (not that I think that will make a difference).

**Comment by simonbrowndotje** [comment]
I'd try updating your JDK 11 installation ... I've found a few references to a similar problem on 11.0.1 and 11.0.2 (I'm using 11.0.6 if that helps).

**Comment by simonbrowndotje** [comment]
I've just installed OpenJDK 11.0.2 and it fails, so you'll need to update your Java installation.

**Comment by dchwartz-optimal** [comment]
Thank you for your help in debugging this.

I will update to 11.0.6 and see if it works

**Comment by dchwartz-optimal** [comment]
As a follow up, I updated to OpenJDK 13 and it works great now

Thank you for your help
